name: Example Workflow - Testing
on: [push]
  # Manual run by SK
 # workflow_dispatch:
  #  inputs:
   #   colour:
    #    type: choice
     #   description: "Pick a colour"
      #  options:
       # - Red
        #- Green
        #- Blue
 
jobs:
  ExampleJob:
    runs-on: KaurSup_laptop
    #runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout this repository
          echo "Checkout this repo"
        uses: actions/checkout@v3
        
      - name: Run the unit test
        run: |
            #cd unit_tests
            #bash ./sample-bash.sh
            bash ./unit_tests/run_L1_full_test.sh
