name: Example Workflow - Testing
on:
  push:
    branches: [ master, main, 'sprint/**', 'release/**' ]

  pull_request:
    # By default: opened, synchronize, or reopened
    branches: [ master, main, 'sprint/**', 'release/**' ]

  schedule:
      - cron: '35 7,19 * * *'
  
  # Manual run by SK
 # workflow_dispatch:
  #  inputs:
   #   colour:
    #    type: choice
     #   description: "Pick a colour"
      #  options:
       # - Red
        #- Green
        #- Blue
 
jobs:
  ExampleJob:
    #runs-on: KaurSup_laptop
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      
      - name: Checkout this repository
          echo "Checkout this repo"
        uses: actions/checkout@v3
        with:
          path: Bundlegen
 
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          cache: 'pip'
      - run: pip install jsonref
      - run: python -m venv .venv
      - run: source .venv/bin/activate
      - run: pip install -r Bundlegen/requirements.txt
      - run: pip install --editable Bundlegen/
      
 
      - name: Run the unit test
        run: |
            #cd unit_tests
            bash ./sample-bash.sh
            #bash ./unit_tests/run_L1_full_test.sh
            python Bundlegen/unit_tests/L1_testing/test_files/test_Bundleprocessor_ut.py
