name: Example Workflow - Testing
on: [push]
  # Manual run by SK
 # workflow_dispatch:
  #  inputs:
   #   colour:
    #    type: choice
     #   description: "Pick a colour"
      #  options:
       # - Red
        #- Green
        #- Blue
        #- Purple
 
jobs:
  ExampleJob:
    runs-on: KaurSup_laptop
    defaults:
      run:
        shell: bash
  
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2
 
    - name: Do some work on the repo
      run: |
        echo "Run some bash code here on laptop"
        ls -al
        echo "You chose ${{ github.event.inputs.colour }}"
