name: L1 unit test

on:
  push:
    branches: [ main, 'sprint/**', 'release/**' ]
    
  pull_request:
    # By default: opened, synchronize, or reopened
    branches: [ master, main, 'sprint/**', 'release/**' ]

  schedule:
      - cron: '35 7,19 * * *'
 
jobs:
  L1-unit-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      
      - name: Checkout this repository
          echo "Checkout this repo"
        uses: actions/checkout@v3
        with:
          path: Bundlegen
 
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          cache: 'pip'
      - run: pip install -r Bundlegen/requirements.txt
      - run: pip install --editable Bundlegen/
      
 
      - name: Run the unit test
        run: |
            #python Bundlegen/unit_tests/L1_testing/test_files/test_Bundleprocessor_ut.py
            python Bundlegen/unit_tests/L1_testing/run_L1_test.py
