name: oci_creation

on:
  push:
    branches: [ master, main, 'sprint/**', 'release/**' ]

  pull_request:
    # By default: opened, synchronize, or reopened.
    branches: [ master, main, 'sprint/**', 'release/**' ]
    
jobs:
  oci_creation:
    name: Create an OCI image
    runs-on: ubuntu-latest
    
    steps:

        
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - run: pip install jsonref
      
      - name: Checkout this repository
          echo "Checkout this repo"
        uses: |
            actions/checkout@v3
            webfactory/ssh-agent@v0.6.0    
        with:
          path: Bundlegen
          ssh-private-key: ${{ secrets.COMCAST_SSH_KEY }}
          
          
          
          
    
      - name: Add SSH key
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
            mkdir -p /home/runner/.ssh
            # Replace example.com with the hostname of the machine
            # you're SSH-ing into
            ssh-keyscan github.com >> /home/runner/.ssh/known_hosts
            # DOKKU_SSH_KEY is the name of the repository secret
            echo "${{ secrets.COMCAST_SSH_KEY }}" > /home/runner/.ssh/github_actions
            chmod 600 /home/runner/.ssh/github_actions
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null   
            ssh-add /home/runner/.ssh/github_actions 

      - name: checkout repo
        uses: Javier-varez/google-repo-action@v0.2
        with:
          manifest-url: 'stagingrdkm/lgpub/'
          manifest-branch: 'master'
          manifest-file: 'manifests/dac-dunfell-3.1.6-manifest.xml'
          manifest-group: 'default'
          checkout-deps: false          
      
      - name: Checkout code using bash script
        run: |
            #cd unit_tests
            pwd
            ls -l
            #bash ./Bundlegen/DAC-SDK-checkout.sh
            
      
#      - name: Checkout DAC-SDK
 #       uses: actions/checkout@v3
              #carbohydrates/init-action@v3
  #      with:
   #       repository: stagingrdkm/lgpub
         # https://github.com/stagingrdkm/lgpub/ -m manifests/dac-dunfell-3.1.6-manifest.xml
   #       path: DAC-SDK
          
      - name: Build dac
        run: |
            ls -l
            cd dac
            ls -l
            cd scripts
            ls -l
            bash ./Build_Oci_Image_Bundle.sh -p raspberrypi3 -a dac-image-wayland-egl-test -b master
