name: SSH setup
on:
  push:
   branches: [ master, main, 'sprint/**', 'release/**' ]

jobs:
  ExampleJob:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.COMCAST_SSH_KEY }}
        name: id_rsa # optional
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        #config: ${{ secrets.CONFIG }} # ssh_config; optional
        if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
