name: Example Workflow - Testing
on:
  push:
    branches: [ master, main, 'sprint/**', 'release/**' ]

  pull_request:
    # By default: opened, synchronize, or reopened
    branches: [ master, main, 'sprint/**', 'release/**' ]

  
  # Manual run by SK

jobs:
  ExampleJob:
    #runs-on: KaurSup_laptop
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    ##- name: Configure SSH key
     # uses: webfactory/ssh-agent@v0.6.0
     # with: 
      #    ssh-private-key: ${{ secrets.COMCAST_SSH_KEY }}
    - uses: actions/checkout@v2
      with:
        ssh-key: "${{ secrets.COMCAST_SSH_KEY }}"
      
    - name: Test ssh
      run: |
            ls -ll
            echo "Running ssh command"
            eval `ssh-agent`
            echo "Running ssh -vT command"
            ssh -vT git@github.com
            echo "Running ssh-add"
            ssh-add -l -E sha256
           
      
    - name: Checkout dwrobel
          echo "Checkout dwrobel repo"
      uses: actions/checkout@v3
      with:
          repository: dwrobel/poky
          path: dwrobel
