name: test.yml
on:
  push:
   branches: [ master, main, 'sprint/**', 'release/**' ]

  pull_request:
    # By default: opened, synchronize, or reopened
    branches: [ master, main, 'sprint/**', 'release/**' ]

  
  # Manual run by SK

jobs:
  ExampleJob:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    ##- name: Configure SSH key
     # uses: webfactory/ssh-agent@v0.6.0
     # with: 
      #    ssh-private-key: ${{ secrets.COMCAST_SSH_KEY }}
   # - uses: actions/checkout@v2
    #  with:
     #   ssh-key: "${{ secrets.COMCAST_SSH_KEY }}"
     
  #  - uses: kielabokkie/ssh-key-and-known-hosts-action@v1
   #   with:
    #      ssh-private-key: ${{ secrets.COMCAST_SSH_KEY }}
     #     ssh-host: github.com
     
     
    - name: Add SSH key
      env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
            echo "where am I ?"
            pwd
            echo " "
            echo " "
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.COMCAST_SSH_KEY }}" > ~/.ssh/id_rsa
            ssh-keyscan -H github.com > ~/.ssh/known_hosts
            eval "$(ssh-agent -s)"
            #ssh-add /home/runner/.ssh/github_actions
            ssh-add ~/.ssh/id_rsa
      
    - name: Test ssh
      run: |
          #  echo "whats in this directory"
           # ls -ll
           echo "whats in runner/.ssh directoy"
           ls -al /home/runner/.ssh/
           echo " "
           echo " "
           echo "whats in ssh directoy"
           ls -al ~/.ssh
           echo " "
           echo " "   
           echo "what are contents of id_rsa"
           cat ~/.ssh/id_rsa
           echo " "
           echo " "            
           echo "whats in known hosts ?"
           cat /home/runner/.ssh/known_hosts
           echo " "
           echo " " 
           # echo "Running ssh command"
           # eval `ssh-agent`
            echo "Running ssh -vT command"
            ssh -vT git@github.com
            #echo "Running ssh-add"
            #ssh-add -l -E sha256
           
      
    - name: Checkout dwrobel
          echo "Checkout dwrobel repo"
      uses: actions/checkout@v3
      with:
          repository: dwrobel/poky
          path: dwrobel
