name: Example Workflow - Testing
on:
  push:
    branches: [ master, main, 'sprint/**', 'release/**' ]

  pull_request:
    # By default: opened, synchronize, or reopened
    branches: [ master, main, 'sprint/**', 'release/**' ]

  
  # Manual run by SK

jobs:
  ExampleJob:
    #runs-on: KaurSup_laptop
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    
    
      - name: Add SSH key
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
            mkdir -p /home/runner/.ssh
            # Replace example.com with the hostname of the machine
            # you're SSH-ing into
            ssh-keyscan github.com >> /home/runner/.ssh/known_hosts
            # COMCAST_SSH_KEY  is the name of the repository secret
            echo "${{ secrets.COMCAST_SSH_KEY }}" > /home/runner/.ssh/github_actions
            chmod 600 /home/runner/.ssh/github_actions
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null   
            ssh-add /home/runner/.ssh/github_actions
    
      - name: Test ssh
        run: |
            ls -ll
            echo "Running ssh command"
            eval `ssh-agent`
            echo "Running ssh -vT command"
            ssh -vT git@github.com
            echo "Running ssh-add"
            ssh-add -l -E sha256
           
      
      - name: Checkout dwrobel
          echo "Checkout dwrobel repo"
        uses: actions/checkout@v3
        with:
          repository: dwrobel/poky
          path: dwrobel
